### ISSUE TITLE
question: where to get protocol code?

### ISSUE THREAD

**Issue by LuozhuZhang** [sismo-core/ens-sdao#48]
Is sismo still beta?

How to check the protocol code?

**Comment by gabin54** [comment]
Hey ! 

You can find the protocol code here : https://github.com/sismo-core/sismo-protocol :)

**Comment by LuozhuZhang** [comment]
> https://github.com/sismo-core/sismo-protocol

Awesome

**Comment by LuozhuZhang** [comment]
I will continue to follow sismo and look forward to researching your zkp backend

You will be a zk-protocol with great potential!
